### ISSUE TITLE
Render multiple colors

### ISSUE THREAD

**Issue by Weasy666** [Weasy666/bevy_svg#1]
A SVG is currently only drawn with a single (the one of the last path) color.
Need to change this by using a custom shader.

**Comment by TheLeonsver1** [comment]
Hey, I think you could use the shader from this example for that: https://github.com/bevyengine/bevy/blob/main/examples/shader/mesh_custom_attribute.rs
I'm not sure, but since it seems to me like you already output the vertex colors to the mesh then if the example works it should probably do the job, no?

**Comment by Weasy666** [comment]
Hm...right, that looks promising! Thanks for the pointer, i will give it a try when i find some time tomorrow.
